# Generated by Django 3.2.13 on 2022-11-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221111_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
