# Generated by Django 3.2.13 on 2022-11-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_cheer_novel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
